name: wishbone-utils-docs
channels:
- SymbiFlow
- conda-forge
- defaults
dependencies:
- doxygen
- netlistsvg
- pango
- pip
- pycairo
- pygobject
- python=3.7
- yosys
- pip:                            # Packages installed from PyPI
  - -r file:requirements.txt
